name: Build for MacOS, Linux and Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nhartland/love-build@v1
        id: love-build
        with:
          app_name: 'pizza_symphony'
          love_version: 11.5
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: ${{ steps.love-build.outputs.macos-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: win32-build
          path: ${{ steps.love-build.outputs.win32-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: win64-build
          path: ${{ steps.love-build.outputs.win64-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: love-build
          path: ${{ steps.love-build.outputs.love-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: linux_x86_64-build
          path: ${{ steps.love-build.outputs.linux_x86_64-filename }}
